#!/usr/bin/expect -f

#-------------------------------------------------------------------------
#-TESTS-------------------------------------------------------------------
#-------------------------------------------------------------------------

# - xv6 timer precision test
# @argv - file name for logging
proc timer_test {argv} {

   send "timer test\n"
   sleep 2
   send "10\n"
   sleep 10
   send "\n"
   expect {
      "$ "
   }
}

#-------------------------------------------------------------------------
#-MAIN--------------------------------------------------------------------
#-------------------------------------------------------------------------

# no limit - usertests are time consuming
set timeout -1

# dry-run to get qemu command - to end qemu with close afterwards
spawn bash -c "make clean"
expect eof
spawn bash -c "make"
expect eof
spawn bash -c "make -n qemu-nox | grep qemu"
expect eof
set qemu_command $expect_out(buffer)

# TODO: use the resut of dry run as an agument fot spawn ($expect_out(buffer) is not working for some reason)
# actual run
spawn qemu-system-i386 -nographic -drive file=fs.img,index=1,media=disk,format=raw -drive file=xv6.img,index=0,media=disk,format=raw -smp 2 -m 512
expect "$ "

#uncomment for expect debugging
#exp_internal 1

set running [timer_test $argv]
